site:
  name: Dylan & Ryan
  site: 'https://rajkoh.github.io'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: # Add your Google verification ID if desired

# Default SEO metadata
metadata:
  title:
    default: Dylan & Ryan - Our Journey to Parenthood
    template: '%s â€” Dylan & Ryan'
  description: "We are Dylan and Ryan, a loving couple from Toronto on a journey to grow our family. We're looking for a compassionate surrogate partner to help make our dream of parenthood a reality."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Dylan & Ryan - Our Journey to Parenthood
    images:
      - url: '/our-family-website/images/Chapter2-1.jpg'
        width: 1200
        height: 800
    type: website
  twitter:
    handle: ''
    site: ''
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/%slug%'
      robots:
        index: false

    list:
      isEnabled: false
      pathname: 'blog'
      robots:
        index: false

    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: false

    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
